### ISSUE TITLE
java.lang.RuntimeException: Game attempted to load serverside rite data from a clientside world.

### ISSUE THREAD

**Issue by Norarabbits** [Favouriteless/Enchanted#11]
Upon attempting to create/join world game crashes.

To recreate - have Enchanted Witchcraft installed

[crash-2023-03-07_23.42.20-client.txt](https://github.com/Favouriteless/Enchanted/files/10917589/crash-2023-03-07_23.42.20-client.txt)

**Comment by TheFieryFalcon** [comment]
Downgrading to Forge 40.2.0 worked for me.
