### ISSUE TITLE
Distillery does not function at all on a server

### ISSUE THREAD

**Issue by Benny-Boo** [Favouriteless/Enchanted#15]
**Describe the bug**
No Distillery recipes work on a server. I think it's because it doesn't know what's the product and what's the input, since REI won't even show the recipe for the product, but if you look at all the Distillery recipes, it does still have the intended items in the recipe.

**To Reproduce**
1. Go on a server
2. Check the Distillery recipes in JEI/REI

**Expected behavior**
Being able to use the Distillery at all.

**Screenshots**
![image](https://github.com/Favouriteless/Enchanted/assets/24782877/8ec84e6e-afcf-4e7d-a7bc-dbda4fc04ee8)
(In a singleplayer world on the same pack)
![image](https://github.com/Favouriteless/Enchanted/assets/24782877/d69959a2-2e41-4d49-8afc-a53c9340c117)
(On a server)

**Comment by Favouriteless** [comment]
Should be fixed in the most recent update, uploading today.
