### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by CobaltGlacier** [Favouriteless/Enchanted#18]
**Describe the bug**

it keeps crashing upon startup, and giving this error code: 

Description: Initializing game

java.lang.NullPointerException: Registry Object not present: enchanted:boiling

**To Reproduce**

im not sure how, it kept doing that and idk what mods caused it

**Expected behavior**

everytime a certain combo of mods are used, it gives this error code

**Screenshots**

[crash-2024-05-19_16.54.27-client.txt](https://github.com/Favouriteless/Enchanted/files/15370914/crash-2024-05-19_16.54.27-client.txt)
[latest.log](https://github.com/Favouriteless/Enchanted/files/15370919/latest.log)

**Comment by Favouriteless** [comment]
Identified a fix, this will be solved when I push the next LTS patch for 1.19.2 so closing this now.
