### ISSUE TITLE
crash on startup (1.20.1 fabric)

### ISSUE THREAD

**Issue by nobus** [Favouriteless/Enchanted#19]
**Describe the bug**
it keeps crashing upon startup, and giving this error in logfile:
```
at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.20.1-84-FABRIC.jar:?]
```

**To Reproduce**
Minecraft 1.20.1, fabric loader 0.15.11

My mods' list:
```
enchanted-fabric-1.20.1-3.0.0.jar
fabric-api-0.92.1+1.20.1.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
geckolib-fabric-1.20.1-4.4.4.jar
Patchouli-1.20.1-84-FABRIC.jar
SmartBrainLib-fabric-1.20.1-1.14.jar
StateObserver-fabric-1.20.1-1.4.0.jar
```
Just run minecraft and it crached =(

**Expected behavior**
If I remove enchanted-fabric-1.20.1-3.0.0.jar from my mod's dir - minecraft will work.

**Screenshots**
[latest.log](https://github.com/Favouriteless/Enchanted/files/15482406/latest.log)

**Comment by Favouriteless** [comment]
Confirmed this happening, thanks for the report. Will try to have this fixed by the followup patch in the next day or two.

**Comment by Favouriteless** [comment]
Fixed, will push the update when I clear the rest of the 1.20.1 bugs.
