### ISSUE TITLE
Crash while loading mod in Multiplayer

### ISSUE THREAD

**Issue by jmsilva90** [Favouriteless/Enchanted#2]
Hey there ! If there's any issue with the format of this bug report, please give feedback. Thanks ! :)

According to the crash log, there's a client feature trying to be loaded into the server, causing it to fail

Load a modpack with Enchanted included onto Multiplayer

[Server] INFO Failure message: Enchanted (enchanted) has failed to load correctly
[Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER

[crash-2022-02-12_13.02.19-fml.txt](https://github.com/Favouriteless/Enchanted/files/8053440/crash-2022-02-12_13.02.19-fml.txt)

**Comment by Favouriteless** [comment]
Known issue, I've fixed it but haven't had time to push the update out properly.

Sorry for the late response
