### ISSUE TITLE
[1.20.1] Several patchouli books are broken

### ISSUE THREAD

**Issue by Not-February** [Favouriteless/Enchanted#22]
Enchanted version: 3.0.4
Mod loader: Forge 47.3.0

**Describe the bug**
Several of the mod's shipped patchouli guidebooks have various errors which make them unusable in-game. The affected books are Witchcraft: Circle Magic, Witchcraft: Extraction, and Witchcraft: Brewing.
**To Reproduce**
Open the aforementioned books in-game and behold the error messages in the book
**Expected behavior**
To be able to select and read categories from the book like the other working books

**Comment by Favouriteless** [comment]
You've provided zero info at all about the error, so I'm just going to paste what the solution is 99% of the time and close this.

> Almost Unified currently changes Enchanted's recipes in a way which breaks them. Please add the following recipe types to the "ignoredRecipeTypes" field in config/almostunified/unify.json: ["enchanted:distilling",   "enchanted:byproduct",   "enchanted:kettle", "enchanted:witch_cauldron",   "enchanted:spinning"].

**Comment by Not-February** [comment]
My apologies, I've worked with Patchouli before so I saw the errors in the books and erroneously thought at a glance that it was a JSON formatting issue that would be easier to troubleshoot by looking at them in-game on a per-guide basis. I didn't see any other issues(including closed ones) on the issue tracker that had anything to do with the Patchouli books, so I assumed it was a new problem with the port to 1.20.1.

I can confirm that when installed on its own, the mod books work as expected, so it was very likely Almost Unified causing the problem.

If I might suggest something, though: If this is a common issue that you've had people report to you, perhaps you could make pinned issue here on the tracker or make a compatibility note on the mod page so that fewer people report it in the future?
