### ISSUE TITLE
Optifine & Geckolib conflict

### ISSUE THREAD

**Issue by teachyyou** [Favouriteless/Enchanted#24]
**Describe the bug**
When Optifine is installed, earmuffs armor piece rendering breaks (it is displayed as a regular iron helmet). 

**To Reproduce**
Install 1.20.1 Forge + Optifine and try to put on the earmuffs

**Comment by Favouriteless** [comment]
Bring it up with the optifine devs, their project is closed source and there's nothing I can do about it.
