### ISSUE TITLE
Grass Blocks are dropping seeds from Enchanted

### ISSUE THREAD

**Issue by unilock** [Favouriteless/Enchanted#26]
**Describe the bug**

When a [Grass Block](https://minecraft.wiki/w/Grass_Block) is broken (even with Silk Touch), seeds from Enchanted occasionally drop from it.

**To Reproduce**

Break a Grass Block.

**Expected behavior**

It only drops one Dirt or Grass Block, depending on whether it was destroyed using an item enchanted with Silk Touch.

**Screenshots**

N/A

***

https://github.com/Favouriteless/Enchanted/blob/536dfe5e2073b4bfdba4e6c5446777441feda19e/common/src/main/java/favouriteless/enchanted/common/lootextensions/GrassLootExtension.java#L15

Perhaps this is supposed to be `Blocks.GRASS`? (known as [Short Grass](https://minecraft.wiki/w/Short_Grass) in 1.20.3+)

**Comment by Favouriteless** [comment]
Fixed, pending next update
