### ISSUE TITLE
Enchanted Broomstick controls Fabric 1.20.1

### ISSUE THREAD

**Issue by GreekKennyS** [Favouriteless/Enchanted#28]
While riding the enchanted broomstick i cant seem to able to go down only if i dismount it
I searched how emoniphs supposed to be maybe there was a correlation but its different :/
So i dont know how you are supposed to able to go down unless you are supposed to just dismount it

**Comment by Favouriteless** [comment]
Check your keybinds menu, this isn't a 1:1 port.
