### ISSUE TITLE
Altar becomes ticking entity and crashes client

### ISSUE THREAD

**Issue by NeverlandSMP** [Favouriteless/Enchanted#3]
When you place the altar block to make it at the last placement the altar turns into a ticking entity and crashes the game client

Place all the altars

Crashes game client

Crash log included
[crash-2022-04-27_07.51.53-client.txt](https://github.com/Favouriteless/Enchanted/files/8571799/crash-2022-04-27_07.51.53-client.txt)

**Comment by Favouriteless** [comment]
I cannot replicate this and have to assume it's an incompatibility with one of the mods in your frankly huge mod list. Are you able to provide the log as well as the crash report?
