### ISSUE TITLE
[BUG]: Crash - Right clicking with any poppet crashes the game

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#35]
### Please confirm the following

- [x] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.0-beta

### Describe the bug

right clicking with any poppet that is not the default one will immediately crash the game

### Game Log

https://gist.github.com/QuinceCat/8ce31597c4f784df3b15218710c64738

### Additional mods

Yes

### Mod List or Modpack

Just enough items

**Comment by QuinceCat** [comment]
Tried again with a taglock in my offhand and it crashed again

**Comment by Favouriteless** [comment]
Fixed, update pushed.
