### ISSUE TITLE
[BUG]: Crash - Creating an Altar crashes the game

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#36]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.0-beta

### Describe the bug

Creating a second Altar in the world will crash the game
Removing the first Altar also crashes the game and bricks the world

### Game Log

https://gist.github.com/QuinceCat/4effba90ed11b4188a01a4fe22c47590

### Additional mods

Yes

### Mod List or Modpack

Just enough Items

**Comment by QuinceCat** [comment]
I cannot replicate this

**Comment by Favouriteless** [comment]
Fixed, update pushed.
