### ISSUE TITLE
[BUG]: minor bug - stalling cauldron recipes and particles

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#37]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.0-beta

### Describe the bug

If you create an item in the cauldron but use a bucket to take water out of it before the particle swirling is done, the particle swirls will continue until the water is returned to full or the cauldron is broken.
if water is returned the recipe will pick back up and will produce the item normally
![image](https://github.com/user-attachments/assets/76bd4269-0048-452f-95b7-fa77c6c7fcfc)

### Additional mods

Yes

### Mod List or Modpack

Just enough items

**Comment by Favouriteless** [comment]
Fixed, update pushed.
