### ISSUE TITLE
[BUG]: minor bug - Position on broom is incorrect

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#38]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.0-beta

### Describe the bug

broom sticking halfway through body 
![image](https://github.com/user-attachments/assets/54ad646d-5c37-40f8-a159-5ca670b10a3c)

### Additional mods

Yes

### Mod List or Modpack

Just enough Items

**Comment by Favouriteless** [comment]
Fixed, update pushed.
