### ISSUE TITLE
[BUG]: crash - Rite of total Eclipse crashes game

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#48]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.2-beta

### Describe the bug

Preforming the rite of total eclipse crashes the game

### Game Log

https://gist.github.com/QuinceCat/849088c1762d2c366ba30fe8f840a233

### Additional mods

Yes

### Mod List or Modpack

just enough items

**Comment by Favouriteless** [comment]
Oh, I already fixed this issue while making command rites.
