### ISSUE TITLE
[BUG]: Crash - using an untamed cat in the familiar rite crashes the game

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#50]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.3-beta

### Describe the bug

using an untamed cat in the familiar rite will crash the game

### Game Log

https://gist.github.com/QuinceCat/b689fdf0350bf490a971d45a2d1db08c

### Additional mods

Yes

### Mod List or Modpack

Just enough Items

**Comment by Favouriteless** [comment]
Fixed
