### ISSUE TITLE
[BUG]: Charged Rite of Broiling uses Altar power

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#51]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.3-beta

### Describe the bug

Rite of broiling with an attuned stone still requires altar power

### Additional mods

Yes

### Mod List or Modpack

just enough Items

**Comment by Favouriteless** [comment]
Fixed for next update
