### ISSUE TITLE
[BUG]: Summoning your familiar to the world border makes it invisible

### ISSUE THREAD

**Issue by QuinceCat** [Favouriteless/Enchanted#52]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.3-beta

### Describe the bug

1. Summon your familiar at 0,0
2. go to 0, 0, 29999999
3. Summon your familiar near the border
You will hear the familiar meow but will not be able to see it, summoning it back to 0,0 will make it reappear, summoning it to another spot near the border does not make it reappear
Relogging makes the familiar appear
Unsure if related, but just in case. When I did this the first time it disconnected me from the 'server' shortly after.

### Game Log

https://gist.github.com/QuinceCat/85f4ab650eec0d5aee278b2ae860e209

### Additional mods

Yes

### Mod List or Modpack

Just enough Items

**Comment by Favouriteless** [comment]
Can't replicate

**Comment by Favouriteless** [comment]
Seems to be a vanilla or loader bug? Client receives the wrong position, not sure why but either way it's nothing to do with Enchanted.
