### ISSUE TITLE
[BUG]: Villager cure crash

### ISSUE THREAD

**Issue by SLPcom** [Favouriteless/Enchanted#56]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

beta 1.21.1-4.0.5 neoforge

### Describe the bug

curing zombie villager will result in java.lang.StackOverflowError

weakness splash potion 4 minutes used. 

without the enchanted mod activated it will result in no crashing. tested both times in a new world.

[crash-2024-12-12_02.26.18-server.txt](https://github.com/user-attachments/files/18104351/crash-2024-12-12_02.26.18-server.txt)

### Additional mods

Yes

### Mod List or Modpack

![image](https://github.com/user-attachments/assets/eb94bf98-18f3-41f8-81de-634f01b18833)

**Comment by Favouriteless** [comment]
Fixed, pushing update now
