### ISSUE TITLE
[BUG]: non-functional rituals 1.21.1

### ISSUE THREAD

**Issue by SLPcom** [Favouriteless/Enchanted#59]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

beta 1.21.1-4.0.7 neoforge

### Describe the bug

it seems the ritual for making the enchanted broom is not functional and will play the noteblock sound for failing ritual. tested without additional mods too with it not being functional

ritual has been tried at night and day. rite of familiar also seems to not be functional with this when putting in all the ingredients. might have to do with it not registering the ingredients as valid, this was once also a bug in the old 1.7.10 witchery mod, cannot think of anything else it might have been.

![image](https://github.com/user-attachments/assets/1dadeadc-391b-463e-b3c4-ae6608b16b87)

### Additional mods

No

**Comment by Favouriteless** [comment]
Worked first try for me, can you try replicating this and sending the log?
![image](https://github.com/user-attachments/assets/2a04aaf3-8930-4a84-95f8-bbbd8423c299)

**Comment by SLPcom** [comment]
i figured it out,

important and this has nothing to do with enchanted but when using SERENE Seasons mod. be wary that any season other than spring will result in failure. removing the mod while it went to any other season will still result in failure for the enchanted mod's rituals even with the mod fully removed and stuff remade. test world had at one point serene on it too before i removed it, but because it went to summer in there it never reverted back and never got remade (which should not happen i believe, remaking a world should complete remove everything even mod data from that in the new copy)
