### ISSUE TITLE
Console SPAM of Saved active rites

### ISSUE THREAD

**Issue by SrRapero720** [Favouriteless/Enchanted#6]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29090346/206809294-74bc6f82-856a-41be-a305-f4956ecf02bb.png)

Console its usefull to find any problem/info about any mod. but when got spammed  a "save of something" get annonyng.
my recomendation is use debug.log file keeping clear console for more important infomation/responses

**Comment by SrRapero720** [comment]
Other suggest is no output any "successfully" log. just keeping everything into a "error happen on normal behavior" so that can be more efficient.

**Comment by Favouriteless** [comment]
Implemented in later versions
