### ISSUE TITLE
[BUG]: Patchouli has errors loading most of the enchanted guide books

### ISSUE THREAD

**Issue by Jankoy** [Favouriteless/Enchanted#60]
### Please confirm the following

- [X] This bug is not in another [current issue](https://github.com/Favouriteless/Enchanted/issues)
- [X] This report is not a general support request. If it is, join the [Discord](https://discord.gg/UkVgJ9nb5y)

### Minecraft version

1.21.1

### Mod version

4.0.7

### Describe the bug

Patchouli has errors creating the guide books, I'm not sure which ones exactly but I know circles and brewing are broken at least.

### Game Log

https://mclo.gs/yHskmWp

### Additional mods

Yes

### Mod List or Modpack

Patchouli and REI.

**Comment by Jankoy** [comment]
Here's what the error in the book says if it's helpful.

```
Error building entry enchanted:binding_waystone of book enchanted:circle_magic

Error while building entry enchanted:binding_waystone page 1 of book enchanted:circle_magic
Failed to create custom component net.favouriteless.enchanted.patchouli.components.RiteRequirementsComponent
net.favouriteless.enchanted.patchouli.components.RiteRequirementsComponent
```

**Comment by Favouriteless** [comment]
Patchouli isn't supported on 1.21.1 and an alternative is being worked on

**Comment by Jankoy** [comment]
Thanks!
