### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by LunaGlaze** [Favouriteless/Enchanted#7]
I like Witchery mod very much, and I'm glad to see you make a mod on Forge as Witchery's successor. Thank you for your efforts on this.
I made a Chinese localization file for your mod according to Witchery's translation in 1.7.10 Chinese community. Can you add it to the lang folder in the next update? I will be very grateful!
[zh_cn.zip](https://github.com/Favouriteless/Enchanted/files/10251856/zh_cn.zip)

**Comment by Favouriteless** [comment]
Sorry for being incredibly late with responding to this, never noticed it until today. Thanks for the help with this, I'll add it asap and have asked for some help from the community for also including patchouli books etc for it.

**Comment by Favouriteless** [comment]
Translations should be in the next version of the mod, thanks again.
