### ISSUE TITLE
Plant Seeds Aren't Dropping from Tall Grass 1.18.2

### ISSUE THREAD

**Issue by toErIpNid** [Favouriteless/Enchanted#8]
While playing multiplayer on a server, the seeds don't seem to be dropping from tall grass, rendering the mod unplayable. 

[test.zip](https://github.com/Favouriteless/Enchanted/files/10369358/test.zip)
Use this export in the curse launcher to explore the issue yourself.

**Comment by AdalynBlack** [comment]
This seems to be an issue in for me currently in 1.20.1 on Forge
I have a download for the modpack here: https://adibtw.duckdns.org:32450/modpacks/create-vs-magic/latest/Modrinth.mrpack

I _think_ it might be a conflict with Occultism, though I'm not fully sure. Based on the occultism drop rate for seeds (2%), I should have ~105 seeds from Enchanted, yet I have 0
